code --install-extension 42Crunch.vscode-openapi
code --install-extension Arjun.swagger-viewer
code --install-extension be5invis.vscode-icontheme-nomo-dark
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-mermaid
code --install-extension cymonk.sql-formatter
code --install-extension dawhite.mustache
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension felixfbecker.php-intellisense
code --install-extension GabrielBB.vscode-lombok
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension hiro-sun.vscode-emacs
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension liximomo.sftp
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mitchdenny.ecdc
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension nickdemayo.vscode-json-editor
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension Pivotal.vscode-boot-dev-pack
code --install-extension Pivotal.vscode-concourse
code --install-extension Pivotal.vscode-manifest-yaml
code --install-extension Pivotal.vscode-spring-boot
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension ryannaddy.laravel-artisan
code --install-extension ryu1kn.partial-diff
code --install-extension scala-lang.scala
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension Unity.unity-debug
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.change-case
code --install-extension yuna611d.grep2file
code --install-extension yzhang.markdown-all-in-one
